civilcomments_small:
    erm:
        num_train_epochs: 50
        learning_rate: 1e-5
        weight_decay: 1e-2
        batch_size: 8
        lr_scheduler_type: 'linear'
    jtt:
        num_train_epochs: 50
        learning_rate: 1e-5
        weight_decay: 1e-2
        batch_size: 8
        up: 6
        T: 5
        lr_scheduler_type: 'linear'
    dro:
        num_train_epochs: 50
        learning_rate: 1e-5
        weight_decay: 1e-2
        batch_size: 32
        lr_scheduler_type: 'linear'
    erm_l1:
        num_train_epochs: 50
        learning_rate: 1e-5
        weight_decay: 1e-2
        batch_size: 32
        erm_weight: 0
        reg_weight: -1
        lr_scheduler_type: 'linear'
    erm_mt:
        num_train_epochs: 50
        learning_rate: 1e-5
        weight_decay: 1e-2
        batch_size: 32
        erm_weight: 0
        mt_weight: -1
        lr_scheduler_type: 'linear'
    erm_mt_l1:
        num_train_epochs: 50
        learning_rate: 1e-5
        weight_decay: 1e-2
        batch_size: 32
        erm_weight: 0
        mt_weight: 0
        reg_weight: -1
        lr_scheduler_type: 'linear'
    erm_mt2_l1:
        num_train_epochs: 50
        learning_rate: 1e-5
        weight_decay: 1e-2
        batch_size: 32
        erm_weight: 0
        mt_weight: -1
        reg_weight: -1
        lr_scheduler_type: 'linear'
             
    
waterbirds:
    erm:
        num_train_epochs: 200
        learning_rate: 1e-3
        weight_decay: 1e-2
        batch_size: 4
        lr_scheduler_type: 'cosine_with_restarts'
    dro:
        num_train_epochs: 200
        learning_rate: 1e-3
        weight_decay: 1e-2
        batch_size: 16
        lr_scheduler_type: 'cosine_with_restarts'
    jtt:
        num_train_epochs: 200
        learning_rate: 1e-3
        weight_decay: 1e-2
        batch_size: 8
        up: 20
        T: 10
        lr_scheduler_type: 'cosine_with_restarts'
    erm_l1:
        num_train_epochs: 200
        learning_rate: 1e-3
        weight_decay: 1e-2
        batch_size: 4
        erm_weight: 0
        reg_weight: -1
        lr_scheduler_type: 'cosine_with_restarts'
    erm_mt:
        num_train_epochs: 200
        learning_rate: 1e-3
        weight_decay: 1e-2
        batch_size: 4
        erm_weight: 0
        mt_weight: 0
        lr_scheduler_type: 'cosine_with_restarts'
    erm_mt_l1:
        num_train_epochs: 200
        learning_rate: 1e-3
        weight_decay: 1e-2
        batch_size: 16
        erm_weight: 0
        mt_weight: -1
        reg_weight: -1
        lr_scheduler_type: 'cosine_with_restarts'
    erm_mt2_l1:
        num_train_epochs: 200
        learning_rate: 1e-3
        weight_decay: 1e-2
        batch_size: 16
        erm_weight: 0
        mt_weight: 1
        reg_weight: -1
        lr_scheduler_type: 'cosine_with_restarts'